name: Publish PDF

on:
  push:
    branches:
      - master
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: |
          ./src/notatka.tex

    - name: Install Ghostscript
      run: sudo apt-get install -y ghostscript

    - name: Combine PDFs
      run: gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -sOutputFile=combined.pdf notatka.pdf media/sciaga.pdf

    - name: Get latest tag
      id: get_latest_tag
      run: echo ::set-output name=tag::$(git describe --tags `git rev-list --tags --max-count=1`)

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_latest_tag.outputs.tag }}
        release_name: Release ${{ steps.get_latest_tag.outputs.tag }}.${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload PDF to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: combined.pdf
        asset_name: combined.pdf
        asset_content_type: application/pdf