name: Publish PDF

on:
  push:
    branches:
      - master
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: |
          ./src/notatka.tex

    - name: Install Ghostscript
      run: sudo apt-get install -y ghostscript

    - name: Combine PDFs
      run: gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -sOutputFile=combined.pdf ./src/notatka.pdf media/sciaga.pdf

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload PDF to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: combined.pdf
        asset_name: combined.pdf
        asset_content_type: application/pdf